name: Main CI workflow

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - master
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: terraform-ls --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
      - run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt@v3.3.0
      - run: shfmt -ci -s -bn bin/*
